apiVersion: v1
kind: PersistentVolume
metadata:
    name: data-local
    labels:
       type: local
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 100Gi
    hostPath:
        path: "/data/k8s"
    persistentVolumeReclaimPolicy: Retain

