apiVersion: v1
data:
  known_hosts: |
    {VALUE_FROM_KNOWN_HOSTS_CONTAINING_DEPLOY_KEY}
  ssh_config: |
    Host *
    StrictHostKeyChecking yes
    IdentityFile /etc/odind/identity
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/ssh-config
