apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rw-many
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: manual 
  resources:
    requests:
      storage: 100Gi
  volumeName: data-local
