apiVersion: v1
kind: PersistentVolume
metadata:
    name: odin-data 
    labels:
       type: local
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 1T
    nfs:
        path: "/data"
        server: {FILE_SERVER_IP}
    persistentVolumeReclaimPolicy: Retain

